---
- name: Pull docker images of spe_major_backend and spe_major_frontend
  hosts: all
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker backend image
      shell: docker pull prith17/spe_major_backend

    - name: pull docker frontend image
      shell: docker pull prith17/spe_major_frontend
      
    - name: running backend container
      shell: docker run -it -d prith17/spe_major_backend
      
    - name: running frontend container
      shell: docker run -it -d prith17/spe_major_frontend
      
